title: 'Gatsby Theme Console'
description: 'Console Theme in Gatsby'
author: 'Harshith Pabbati'
authoremail: 'pabbatiharshith@gmail.com'
authorirc: 'username'
about:  !markdown |
  #### Gatsby Theme Console